# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-21 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='shcode',
            field=models.CharField(default='code', max_length=50),
        ),
    ]
