# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_data_shcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.CharField(default='date', max_length=50),
        ),
    ]
