# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shcode', models.CharField(default='code', max_length=50)),
                ('date', models.CharField(default='date', max_length=50)),
                ('open', models.IntegerField()),
                ('high', models.IntegerField()),
                ('low', models.IntegerField()),
                ('close', models.IntegerField()),
                ('sign', models.IntegerField()),
                ('change', models.IntegerField()),
                ('diff', models.FloatField()),
                ('volume', models.IntegerField()),
                ('diff_vol', models.FloatField()),
                ('chdegree', models.FloatField()),
                ('sojinrate', models.FloatField()),
                ('changerate', models.FloatField()),
                ('fpvolume', models.IntegerField()),
                ('covolume', models.IntegerField()),
                ('value', models.IntegerField()),
                ('ppvolume', models.IntegerField()),
                ('o_sign', models.IntegerField()),
                ('o_change', models.IntegerField()),
                ('o_diff', models.FloatField()),
                ('h_sign', models.IntegerField()),
                ('h_change', models.IntegerField()),
                ('h_diff', models.FloatField()),
                ('l_sign', models.IntegerField()),
                ('l_change', models.IntegerField()),
                ('l_diff', models.FloatField()),
                ('marketcap', models.IntegerField()),
            ],
        ),
    ]
